In [1]:
import TTC_helper

In [2]:
route_506 = TTC_helper.TTC_line('506')

In [3]:
route_506.getDelayRecord('2022')

,Date,Line,Time,Day,Location,Incident,Min Delay,Min Gap,Bound,Vehicle,lat,lon
20,2022-01-01,506,09:04,Saturday,HOWARD PARK AND RONCES,Operations,9,18,NaN,0,NaN,NaN
23,2022-01-01,506,09:29,Saturday,COLLEGE AND LANSDOWNE,Operations,9,18,NaN,4535,43.6511699,-79.4398699
30,2022-01-01,506,11:54,Saturday,COLLEGE AND LANSDOWNE,Operations,9,18,W,4541,43.6511699,-79.4398699
32,2022-01-01,506,12:38,Saturday,LANSDOWNE AND COLLEGE,Operations,8,16,N,4528,43.6511699,-79.4398699
36,2022-01-01,506,13:43,Saturday,MAIN STATION,Operations,6,12,E,3197,43.6888599,-79.3018
...,...,...,...,...,...,...,...,...,...,...,...,...
17596,2022-12-30,506,18:16,Friday,MAIN STREET STATION,General Delay,10,20,NaN,4436,43.6888599,-79.3018
17601,2022-12-30,506,21:52,Friday,HIGH PARK LOOP,Security,10,20,E,4506,43.6476799,-79.45804
17606,2022-12-30,506,01:33,Friday,QUEEN AND RONCESVALLES,Emergency Services,0,0,W,4586,NaN,NaN
17612,2022-12-31,506,07:35,Saturday,BROADVIEW AND GERRAD,General Delay,10,20,N,4596,NaN,NaN
17620,2022-12-31,506,12:16,Saturday,CASTLE FRANK STATION,Utilized Off Route,6,12,NaN,8810,NaN,NaN

In [4]:
route_506.getDelayRecord('2024')

,Date,Line,Time,Day,Location,Incident,Min Delay,Min Gap,Bound,Vehicle,lat,lon
8,2024-01-01,506,04:53,Monday,RONCESVALLE YARD,General Delay,13,28,E,4408,NaN,NaN
13,2024-01-01,506,05:05,Monday,RONCESVALLES YARD,General Delay,10,20,E,4574,NaN,NaN
21,2024-01-01,506,05:31,Monday,GERRARD AND LOGAN,General Delay,10,20,NaN,4466,43.66716,-79.3450799
24,2024-01-01,506,05:51,Monday,RONCESVALLES YARD,Held By,7,17,W,4542,NaN,NaN
52,2024-01-01,506,21:22,Monday,DUNDAS AND STERLING,Diversion,8,18,NaN,0,43.6506799,-79.44278
...,...,...,...,...,...,...,...,...,...,...,...,...
14186,2024-12-31,506,13:01,Tuesday,GERRARD AND RIVER,General Delay,441,451,W,4605,43.6638199,-79.35905
14189,2024-12-31,506,13:14,Tuesday,HOWARD PARK AND PARKSI,Diversion,23,33,W,4420,NaN,NaN
14192,2024-12-31,506,14:10,Tuesday,GERRARD AND RIVER,Operations,31,41,W,4565,43.6638199,-79.35905
14198,2024-12-31,506,21:07,Tuesday,GERRARD AND SUMACH,Emergency Services,22,32,E,4585,43.6632699,-79.36127
14202,2024-12-31,506,22:32,Tuesday,CARLTON AND JARVIS,General Delay,0,0,NaN,0,43.66251,-79.3765699

In [5]:
route_506.displayDensityMap('2024')

In [6]:
route_509 = TTC_helper.TTC_line('509')

In [8]:
route_509.getDelayRecord('2022')

,Date,Line,Time,Day,Location,Incident,Min Delay,Min Gap,Bound,Vehicle,lat,lon
65,2022-01-01,509,21:38,Saturday,CNE LOOP,Cleaning - Unsanitary,9,18,E,4468,NaN,NaN
109,2022-01-02,509,14:30,Sunday,CNE LOOP,Operations,7,14,W,4416,NaN,NaN
136,2022-01-02,509,21:21,Sunday,CNE LOOP,Mechanical,9,18,E,4440,NaN,NaN
144,2022-01-02,509,01:21,Sunday,EXHIBITION LOOP,Cleaning - Unsanitary,10,20,W,4486,43.63587,-79.4170499
157,2022-01-03,509,08:11,Monday,QUEENS QUAY AND YORK,Security,46,52,W,4468,43.63649,-79.3972999
...,...,...,...,...,...,...,...,...,...,...,...,...
17566,2022-12-29,509,23:00,Thursday,EXHIBITION LOOP,Security,0,0,N,4542,43.63587,-79.4170499
17580,2022-12-30,509,11:58,Friday,UNION STATION,Security,11,19,W,4406,43.6456499,-79.37921
17633,2022-12-31,509,19:08,Saturday,COXWELL AND GERRARD,General Delay,21,31,W,4556,NaN,NaN
17646,2022-12-31,509,00:05,Saturday,QUEENS QUAY AND YORK,Emergency Services,10,20,W,4494,43.63649,-79.3972999
17648,2022-12-31,509,01:12,Saturday,QUEENS QUAY AND HARBOU,Utilized Off Route,10,20,W,4402,43.63649,-79.3972999

In [9]:
route_509.displayDensityMap('2022')